### ISSUE TITLE
The datasource does not support alerting queries

### ISSUE THREAD

**Issue by wuyinggui** [GoshPosh/grafana-meta-queries#109] opened 2020-08-20 09:02 UTC
Use this plugin,I have the timeseries errorpercent chart
many thanks!
Now I want to have an metric alert upon threshold,But grafana says "The datasource does not support alerting queries
"
Need help.

**Comment by Gauravshah** [comment] 2020-08-20 12:45
duplicate of https://github.com/GoshPosh/grafana-meta-queries/issues/19

**Closed by Gauravshah** 2020-08-20 12:45 UTC
