### ISSUE TITLE
The datasource does not support alerting queries

### ISSUE THREAD

**Issue by audriusbugas** [GoshPosh/grafana-meta-queries#43] opened 2018-10-28 09:52 UTC

**Comment by audriusbugas** [comment] 2018-10-28 09:52
Basically alerts are not possible. That would be very useful. Especially with ElasticSearch integration

**Comment by Gauravshah** [comment] 2018-10-29 01:56
duplicate of  https://github.com/GoshPosh/grafana-meta-queries/issues/19

**Closed by Gauravshah** 2018-10-29 01:56 UTC
