### ISSUE TITLE
Arithmetic: Broken numbers possible

### ISSUE THREAD

**Issue by benhartwich** [GoshPosh/grafana-meta-queries#150] opened 2022-06-04 20:18 UTC
Hi,

 I am trying to get broken numbers by using arithmetic like D['in-complete']/C['in-start']. If I use table for visualizing my results I get NaN. Are broken numbers supported?

**Comment by Gauravshah** [comment] 2022-06-05 00:57
duplicate of https://github.com/GoshPosh/grafana-meta-queries/issues/101

**Closed by Gauravshah** 2022-06-05 00:57 UTC

**Comment by benhartwich** [comment] 2022-06-07 06:07
Sorry, I didn´t get, what might be the right solution. My time interval has already reached the maximum.

**Comment by Gauravshah** [comment] 2022-06-07 09:56
if your C is NaN I am not sure how do you want to present it on your graph. But lets say you want to plot a 0 it can be done as follows:
`(C['in-start']>0) D['in-complete']/C['in-start'] : 0`
