### ISSUE TITLE
MetaQueries not displaying data with "--Mixed--" datasource selected

### ISSUE THREAD

**Issue by adrianchase** [GoshPosh/grafana-meta-queries#115] opened 2020-10-26 08:56 UTC
Good morning,

I am trying to make a simple aritmetic operation with two variables in MetaQueries (_A['variable 1']/B['variable 2']_).
Well the issue I think it comes because each of the variables comes from a different datasource - Therefore the data source selected is "--Mixed--": 

![image](https://user-images.githubusercontent.com/46241071/97151169-6b10bd80-176f-11eb-9c4a-b8bea38fd9d0.png)

Here it is the definition of both variables:

**Query A - ALIAS BY "variable 1"**
Description: absolute counter for the parts produced over the lifecycle of the machine  // with the transformation "difference" I extract relative values per day.
Datasource 1: "ConditionMonitoring"
![image](https://user-images.githubusercontent.com/46241071/97151684-22a5cf80-1770-11eb-8811-a4e61d6656fe.png)

**Query B - ALIAS BY "variable 2"**
Description: absolute counter for the energy consumption (electricity) over the lifecycle of the machine // with the transformation "difference" I extract relative values per day.
Datasource 2: "EnergyConsumption"
![image](https://user-images.githubusercontent.com/46241071/97151784-4832d900-1770-11eb-8b7b-8a5083144cd1.png)

**MetaQueries query:**
![image](https://user-images.githubusercontent.com/46241071/97151971-87612a00-1770-11eb-8391-7f797f0c78ca.png)

Note: each variable is displayed in the right way however I receive nothing when I hide all variables except the calculated one:
 
![image](https://user-images.githubusercontent.com/46241071/97152254-eaeb5780-1770-11eb-8d35-8a94c69b0627.png)

![image](https://user-images.githubusercontent.com/46241071/97152295-f63e8300-1770-11eb-8993-ea55e526dadb.png)

![image](https://user-images.githubusercontent.com/46241071/97152221-e161ef80-1770-11eb-8055-8d5ddb2508a5.png)

Furthermore, I have tried to make a simpler calculation (_A['variable 1']*2_) with the same result.

Has anyone faced this issue? Is there anything wrong in the definition?

Thanks a lot in advance!

Best Regards
Adrián

**Comment by Gauravshah** [comment] 2020-10-26 09:06
duplicate of https://github.com/GoshPosh/grafana-meta-queries/issues/114

**Closed by Gauravshah** 2020-10-26 09:06 UTC
