### ISSUE TITLE
Compatibility with alerts

### ISSUE THREAD

**Issue by JJMVG** [GoshPosh/grafana-meta-queries#75] opened 2019-09-18 15:07 UTC
It would be fantastic if it was possible to set alerts based on a percentage threshold set by arithmetics. Currently when try to do this it says "Datasource not supported".

**Comment by Gauravshah** [comment] 2019-09-18 16:55
closing as duplicate of https://github.com/GoshPosh/grafana-meta-queries/issues/19

@JJMVG alerting cannot be supported until grafana backend supports multi-data source backed plugin

**Closed** 2019-09-18 16:55 UTC
