### ISSUE TITLE
Arithmetic not working for Singlestat

### ISSUE THREAD

**Issue by Teots** [GoshPosh/grafana-meta-queries#18] opened 2018-03-02 14:25 UTC
I've seen similar issues in the existing issues, but none of them provided any explanation on how to fix it/do it properly. 

For this example I created a Singlestat named `A` and in a second one I want to show `A * 3`. Very basic and simple.

![screenshot 2018-03-02 15 18 56](https://user-images.githubusercontent.com/2549326/36903323-b496585e-1e2d-11e8-8fd5-46f16098a4ad.png)

The internal config of the second - not working - Singlestat panel can be seen here:

![screenshot 2018-03-02 15 18 33](https://user-images.githubusercontent.com/2549326/36903355-cc359e48-1e2d-11e8-86ca-21650758340f.png)

How can I get this working? Any suggestions?

**Comment by artjomzab** [comment] 2019-02-07 11:04
https://github.com/GoshPosh/grafana-meta-queries/issues/16

**Comment by Gauravshah** [comment] 2020-06-23 10:16
closing as a duplicate of #16

**Closed by Gauravshah** 2020-06-23 10:16 UTC
