### ISSUE TITLE
Only queries that return single series/table is supported

### ISSUE THREAD

**Issue by amandagmsd** [GoshPosh/grafana-meta-queries#96] opened 2020-04-07 14:17 UTC
I'm using two different elasticsearch database.
When using the MetaQueries datasource on a singlestat panel it appears Only queries that return single series/table is supported.
What am I doing wrong?
![A5C137D3-72E5-4CA3-9D4B-6A25013B36E7](https://user-images.githubusercontent.com/22913839/78680010-52b77f00-78c1-11ea-8b12-4e8115f49e1c.png)

**Comment by Gauravshah** [comment] 2020-04-07 14:31
duplicate of https://github.com/GoshPosh/grafana-meta-queries/issues/10

**Closed by Gauravshah** 2020-04-07 14:31 UTC
