### ISSUE TITLE
Signing issue with version 0.0.5 

### ISSUE THREAD

**Issue by SajjadRashid** [GoshPosh/grafana-meta-queries#142] opened 2022-02-03 18:32 UTC
Hi, is it possible for the author to sign this version, please?

![image](https://user-images.githubusercontent.com/96260772/152406448-85a7f0fc-8cb2-4b2f-be0a-77ab950356d8.png)

**Comment by carlossanchezbailon** [comment] 2022-02-04 09:46
+1

**Comment by Gauravshah** [comment] 2022-02-14 09:30
duplicate of https://github.com/GoshPosh/grafana-meta-queries/issues/120

**Closed by Gauravshah** 2022-02-14 09:30 UTC

**Comment by ritubajaj89** [comment] 2022-02-28 08:22
+1

**Comment by SajjadRashid** [comment] 2022-03-03 16:21
Ok, I only saw that nothing happened for very long time so pushed for new ticket. Will look into the fix
