### ISSUE TITLE
MetaQueriesDatasource.query infinite loop in grafana 6.3

### ISSUE THREAD

**Issue by justinvdm** [GoshPosh/grafana-meta-queries#67] opened 2019-08-20 14:19 UTC
`MetaQueriesDatasource` appears to rely on the [`name` property being assigned](https://github.com/GoshPosh/grafana-meta-queries/blob/master/src/datasource.js#L51) in order to tell whether it is dealing with itself, or with a different data source.

Since `6.3` however, grafana seems to [no longer assign `name`](https://github.com/grafana/grafana/compare/v6.2.5...v6.3.0#diff-894468679ebfe67fc2c22f7575f9e2c2L69).

As a result, [this logic branch](https://github.com/GoshPosh/grafana-meta-queries/blob/master/src/datasource.js#L52) is never reached, and the `MetaQueriesDatasource` instance ends up calling `.query` on itself indefinitely.

**Comment by Gauravshah** [comment] 2019-08-20 14:20
duplicate of https://github.com/GoshPosh/grafana-meta-queries/issues/56

**Closed by Gauravshah** 2019-08-20 14:20 UTC

**Comment by justinvdm** [comment] 2019-08-20 14:22
Woops, sorry for missing this, and thank you for the quick reply.

**Comment by Gauravshah** [comment] 2019-08-20 14:24
Thank for finding out the details. I am unable to load the grafana diff due to timeout. Can you point to the commit that changed this behaviour ? It doesn't seem documented

**Comment by justinvdm** [comment] 2019-08-20 14:48
Sure :) It was [1d7bb2a](https://github.com/grafana/grafana/commit/1d7bb2a#diff-894468679ebfe67fc2c22f7575f9e2c2).

**Comment by Gauravshah** [comment] 2019-08-20 14:50
thank you @justinvdm
