### ISSUE TITLE
Update plugin on grafana 

### ISSUE THREAD

**Issue by Snowing** [GoshPosh/grafana-meta-queries#126] opened 2021-03-01 05:35 UTC
https://grafana.com/grafana/plugins/goshposh-metaqueries-datasource

Plugin version seems outdated when using
`grafana-cli plugins install`

**Comment by Gauravshah** [comment] 2021-03-01 05:36
duplicate of https://github.com/GoshPosh/grafana-meta-queries/issues/120

**Closed by Gauravshah** 2021-03-01 05:36 UTC
